// External weekly projections (Sleeper) — pure helpers.
// These are EXTERNAL numbers, never generated by this app; every surface
// that shows them labels the source and week.

// Which week's projections matter right now: current week in-season,
// week 1 of the upcoming season during draft prep.
export function projectionWeek(sleeperState) {
  const season = Number(sleeperState?.season ?? new Date().getFullYear());
  const inSeason = ['regular', 'post'].includes(sleeperState?.season_type);
  return { season, week: inSeason ? (Number(sleeperState?.week) || 1) : 1 };
}

// Stat keys worth carrying to the UI (position-appropriate subsets shown).
const DETAIL_KEYS = [
  'pass_att', 'pass_cmp', 'pass_yd', 'pass_td', 'pass_int',
  'rush_att', 'rush_yd', 'rush_td',
  'rec_tgt', 'rec', 'rec_yd', 'rec_td',
  'fga', 'fgm', 'xpm',
];

// snapshot: { season, week, projections: { <sleeper_id>: {stat: value} } }
// Join is by meta.sleeper_id — exact, no name matching.
export function attachProjections(players, snapshot) {
  const map = snapshot?.projections ?? {};
  let attached = 0;
  for (const p of players) {
    const proj = p.meta?.sleeper_id != null ? map[p.meta.sleeper_id] : null;
    if (proj && proj.pts_ppr != null) {
      const detail = {};
      for (const k of DETAIL_KEYS) if (proj[k] != null && proj[k] !== 0) detail[k] = Math.round(proj[k] * 10) / 10;
      p.projection = {
        season: snapshot.season ?? null,
        week: snapshot.week ?? null,
        pts_ppr: Math.round(proj.pts_ppr * 10) / 10,
        detail,
      };
      attached++;
    } else {
      p.projection = null;
    }
  }
  return { attached };
}
