// AI chat, grounded in the app's actual data.
//
// Primary path: Claude via the official Anthropic SDK (credentials resolved
// from the environment: ANTHROPIC_API_KEY / auth token / `ant` profile).
// Fallback path: a deterministic query engine over the same structured data,
// so the chat still answers the common questions with zero configuration.
import Anthropic from '@anthropic-ai/sdk';
import { buildChatContext } from './context.js';

const MODEL = 'claude-opus-5';

const SYSTEM = `You are the analysis assistant inside a fantasy football Draft Value Finder (10-team PPR, 2026 draft).

Hard rules:
- Answer ONLY from the JSON data context in the user message. Never invent statistics, news, injuries, rankings, or projections. If the context does not contain what you need, say "Data unavailable" for that part.
- Show the numbers behind every claim (e.g. "snap share 61% season -> 74% last 3").
- Always distinguish sources: ADP and expert ranks are external market data; "ai_rank", "ai_confidence" and sleeper states are generated by this app's deterministic engine. Confidence percentages measure evidence strength, not probability of success.
- The user's personal ranks ("my_rank") are theirs. Never tell them to change one; when they disagree with the AI rank, explain both sides of the disagreement.
- Favor sustainable opportunity (snaps, targets, touches) over noisy fantasy-point spikes.
- Be concise and direct. Plain prose, short lists where helpful. The user makes the final decision.`;

let client = null;
function getClient() {
  if (!client) client = new Anthropic();
  return client;
}

export async function chat({ message, history = [], db, assessments, state }) {
  const context = buildChatContext({ message, db, assessments, state });

  try {
    const messages = [
      ...history.slice(-10).map(m => ({ role: m.role, content: m.content })),
      {
        role: 'user',
        content: `DATA CONTEXT (authoritative, current):\n${JSON.stringify(context)}\n\nUSER QUESTION: ${message}`,
      },
    ];
    const response = await getClient().beta.messages.create({
      model: MODEL,
      max_tokens: 1500,
      system: SYSTEM,
      betas: ['server-side-fallback-2026-07-01'],
      fallbacks: 'default',
      messages,
    });
    if (response.stop_reason === 'refusal') {
      return { source: 'claude', text: 'The model declined to answer this request. Try rephrasing your question.' };
    }
    const text = response.content.filter(b => b.type === 'text').map(b => b.text).join('\n');
    return { source: 'claude', model: response.model, text };
  } catch (err) {
    // Client construction throws before any request when no credentials
    // (API key / auth token / profile) can be resolved from the environment.
    const noCreds = /could not resolve authentication/i.test(err?.message ?? '');
    if (noCreds || err instanceof Anthropic.AuthenticationError) {
      const fb = deterministicAnswer(message, context);
      return { source: 'fallback', note: 'No Anthropic API credentials found — answered by the built-in query engine. Set ANTHROPIC_API_KEY for full conversational chat.', text: fb };
    }
    if (err instanceof Anthropic.APIConnectionError) {
      return { source: 'fallback', note: 'Could not reach the Anthropic API — answered by the built-in query engine.', text: deterministicAnswer(message, context) };
    }
    if (err instanceof Anthropic.RateLimitError) {
      return { source: 'error', text: 'Rate limited by the Anthropic API — try again in a moment.' };
    }
    throw err;
  }
}

// ---- deterministic fallback: answers the common query shapes from data ----

const POS_WORDS = { qb: 'QB', quarterback: 'QB', rb: 'RB', 'running back': 'RB', wr: 'WR', receiver: 'WR', 'wide receiver': 'WR', te: 'TE', 'tight end': 'TE', k: 'K', kicker: 'K', dst: 'DST', defense: 'DST' };

function fmtRow(r) {
  const bits = [`${r.name} (${r.pos} ${r.team ?? '?'}, bye ${r.bye ?? '?'})`];
  bits.push(`ADP #${r.adp_rank ?? '—'}, expert #${r.expert_rank ?? '—'}, AI #${r.ai_rank ?? '—'} (${r.ai_confidence ?? '—'}% confidence, AI-generated)`);
  if (r.usage_trend && r.usage_trend !== 'flat') bits.push(`usage: ${r.usage_trend}`);
  if (r.sleeper_state !== 'none') bits.push(`signal: ${r.sleeper_state}`);
  if (r.injury) bits.push(`injury: ${r.injury}`);
  return '- ' + bits.join(' | ');
}

export function deterministicAnswer(message, context) {
  const q = message.toLowerCase();

  if (context.mentioned_players.length) {
    const p = context.mentioned_players[0];
    const lines = [
      `${p.name} (${p.pos}, ${p.team ?? 'FA'}, bye ${p.bye ?? '?'})`,
      `Market: ADP #${p.adp_rank ?? '—'} | Expert #${p.expert_rank ?? '—'} | AI #${p.ai_rank ?? '—'} (${p.ai_confidence}% confidence — AI-generated, measures evidence strength)`,
      p.my_rank != null ? `Your personal rank: #${p.my_rank}` : null,
      '',
      'AI factors:',
      ...p.ai_factors.map(f => '- ' + f),
    ].filter(x => x != null);
    if (typeof p.trend === 'object') {
      lines.push('', `Last-3 window (weeks ${p.trend.last3_weeks.join(', ')}):`,
        `- Snap share: ${pct(p.trend.season_per_game.snap_pct)} season -> ${pct(p.trend.last3_per_game.snap_pct)} last 3`,
        `- Opportunities/g: ${p.trend.season_per_game.opportunities ?? '—'} -> ${p.trend.last3_per_game.opportunities ?? '—'}`,
        `- PPR/g: ${p.trend.season_per_game.ppr ?? '—'} -> ${p.trend.last3_per_game.ppr ?? '—'}`);
    } else if (typeof p.trend === 'string') {
      lines.push('', `Trend: ${p.trend}`);
    }
    return lines.join('\n');
  }

  const posMatch = Object.entries(POS_WORDS).find(([w]) => q.includes(w));
  if (posMatch && /best|top|remaining|available|who/.test(q)) {
    const pos = posMatch[1];
    const rows = context.top_available.filter(r => r.pos === pos && !r.drafted).slice(0, 8);
    if (!rows.length) return `No available ${pos}s left in the top-250 universe.`;
    return `Best available ${pos}s by AI rank (AI-generated; ADP/expert ranks are external):\n` + rows.map(fmtRow).join('\n');
  }

  if (/sleeper|breakout|late.round|undervalued|steal/.test(q)) {
    const rows = context.sleepers_and_emerging.filter(r => (r.adp_rank ?? 999) > 60).slice(0, 10);
    if (!rows.length) return 'No late-round sleeper signals in the current data.';
    return 'Late-round players with active usage signals (snaps AND opportunities rising = signal; partial evidence = emerging):\n' + rows.map(fmtRow).join('\n');
  }

  if (/usage|snaps|rising|increas|trend/.test(q)) {
    const rows = context.top_available.filter(r => ['rising', 'mixed-up'].includes(r.usage_trend)).slice(0, 12);
    if (!rows.length) return 'No available players currently show rising usage in the last-3-game window.';
    return 'Available players with rising usage (last 3 games of 2025 vs season):\n' + rows.map(fmtRow).join('\n');
  }

  if (/recommend|pick|draft|who should/.test(q)) {
    const recs = context.current_recommendations.slice(0, 5);
    const warn = context.draft.position_warnings;
    return [
      `Recommendations for pick #${context.draft.current_pick} (round ${context.draft.round}):`,
      ...recs.map(r => `- ${r.name} (${r.position}) — confidence ${r.confidence}% (AI-generated). Why: ${r.why[0] ?? 'see board'}${r.risk.length ? `. Risk: ${r.risk[0]}` : ''}`),
      ...(warn.length ? ['', 'Roster warnings:', ...warn.map(w => '- ' + w)] : []),
    ].join('\n');
  }

  return [
    'Built-in query engine (no API key configured). I can answer:',
    '- "best remaining WRs" / any position',
    '- "find me a late-round sleeper"',
    '- "show me players whose usage is increasing"',
    '- "who should I draft" (roster-aware recommendations)',
    '- any player\'s name for their full profile',
  ].join('\n');
}

function pct(v) { return v == null ? '—' : `${Math.round(v * 100)}%`; }
