// Builds the grounded data context handed to the AI chat.
// The chat may ONLY reason over what this module returns — that is how we
// guarantee it cannot invent statistics or rankings.
import { recommendations } from '../analyze/recommend.js';
import { rosterSummary } from '../analyze/roster.js';
import { nameKey } from '../normalize/names.js';

function compactRow(p, a, state) {
  return {
    name: p.name, pos: p.position, team: p.team, bye: p.bye,
    adp: p.adp?.overall ?? null, adp_rank: p.adp?.rank ?? null,
    expert_rank: p.expert?.rank ?? null, expert_tier: p.expert?.tier ?? null,
    ai_rank: a.ai_rank, ai_confidence: a.confidence,
    usage_trend: a.trend.available ? a.trend.usage : 'no 2025 data',
    sleeper_state: a.signal.state,
    injury: p.meta?.injury_status ?? null,
    drafted: state.drafted.includes(p.id),
    my_rank: state.personalRanks[p.id] ?? null,
  };
}

function detailedPlayer(p, a, state) {
  return {
    ...compactRow(p, a, state),
    changed_team: p.changed_team ? `2025 team was ${p.team_2025}` : false,
    ai_factors: a.factors.map(f => `[${f.effect}] ${f.text}`),
    trend: a.trend.available ? {
      season_per_game: a.trend.season,
      last3_per_game: a.trend.recent,
      last3_weeks: a.trend.recent.weeks,
      deltas: a.trend.deltas,
      flags: a.trend.flags,
      notes: a.trend.notes,
    } : a.trend.reason,
    sleeper_signal: { state: a.signal.state, reason: a.signal.reason, context: a.signal.context.map(c => c.text) },
    game_log: (p.games ?? []).map(g =>
      `wk${g.week} vs ${g.opponent}: snaps ${g.snap_pct != null ? Math.round(g.snap_pct * 100) + '%' : '?'}, tgt ${g.targets ?? '-'}, rec ${g.receptions ?? '-'}, car ${g.carries ?? '-'}, ppr ${g.fantasy_points_ppr ?? '-'}`),
  };
}

export function buildChatContext({ message, db, assessments, state }) {
  const players = db.players;
  const msgKey = nameKey(message);

  // Players explicitly mentioned in the message get their full profile.
  const mentioned = players.filter(p => {
    const nk = nameKey(p.name);
    const last = nk.split(' ').pop();
    return msgKey.includes(nk) || (last.length > 3 && msgKey.includes(last));
  }).slice(0, 5);

  const available = players.filter(p => !state.drafted.includes(p.id));
  const recs = recommendations(players, assessments, state, { count: 6, mode: db.mode ?? 'draft' });
  const myPlayers = players.filter(p => state.mine.includes(p.id));

  return {
    meta: {
      data_built_at: db.built_at,
      sources: Object.fromEntries(Object.entries(db.sources).map(([k, v]) => [k, `${v?.source ?? 'unknown'} (fetched ${v?.fetched_at ?? '?'})`])),
      note: db.mode === 'season'
        ? `SEASON MODE, week ${db.week ?? '?'} of ${db.season}. Stats are ${db.stats_season} regular season (updated weekly); "baseline" comparisons use ${db.baseline_season} per-game averages. Expert ranks are rest-of-season consensus; ADP is a stale draft artifact. "drafted" means rostered in the league; available players are free agents. AI ranks/confidence are generated by this app's deterministic engine, not an external source.`
        : `DRAFT MODE for the ${db.season} season. Stats are ${db.stats_season} regular season. ADP/expert ranks are the current draft market. AI ranks/confidence are generated by this app's deterministic engine, not an external source.`,
    },
    draft: {
      current_pick: recs.current_pick,
      round: recs.round,
      my_roster: myPlayers.map(p => `${p.name} (${p.position}, bye ${p.bye})`),
      roster_needs: rosterSummary(myPlayers).needs,
      position_warnings: recs.position_warnings,
    },
    current_recommendations: recs.recommendations,
    mentioned_players: mentioned.map(p => detailedPlayer(p, assessments.get(p.id), state)),
    top_available: available.slice(0, 80).map(p => compactRow(p, assessments.get(p.id), state)),
    sleepers_and_emerging: available
      .filter(p => ['signal', 'emerging'].includes(assessments.get(p.id).signal.state))
      .slice(0, 30)
      .map(p => compactRow(p, assessments.get(p.id), state)),
  };
}
